title: Graphs&Data Seminar @TU Delft
description: This is a series of seminars/talks bringing together people from all TU Delft doing research on Graphs and Data who could benefit from the interchange of ideas with colleagues on different topics.   
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman